import request from '@/utils/request'

export const getSummary = (p) => request({ url: '/api/digital-resources/summary', method: 'get', params: p })
export const getList = (p) => request({ url: '/api/digital-resources', method: 'get', params: p })
export const getDetail = (id) => request({ url: `/api/digital-resources/${id}`, method: 'get' })
export const updateMeta = (id, data) => request({ url: `/api/digital-resources/${id}`, method: 'put', data })
export const softDelete = (id) => request({ url: `/api/digital-resources/${id}`, method: 'delete' })
export const restore = (id) => request({ url: `/api/digital-resources/${id}/restore`, method: 'post' })
export const permanentDelete = (id) => request({ url: `/api/digital-resources/${id}/permanent`, method: 'delete' })
export const getOperations = (id) => request({ url: `/api/digital-resources/${id}/operations`, method: 'get' })
export const addRelation = (id, data) => request({ url: `/api/digital-resources/${id}/relations`, method: 'post', data })
export const removeRelation = (relId) => request({ url: `/api/digital-resources/relations/${relId}`, method: 'delete' })
export const setPrimary = (relId) => request({ url: `/api/digital-resources/relations/${relId}/set-primary`, method: 'post' })
export const getVersions = (id) => request({ url: `/api/digital-resources/${id}/versions`, method: 'get' })
export const setTags = (id, data) => request({ url: `/api/digital-resources/${id}/tags`, method: 'post', data })
export const getAllTags = () => request({ url: '/api/digital-resources/tags', method: 'get' })
export const createTag = (data) => request({ url: '/api/digital-resources/tags', method: 'post', data })
export const batchTags = (data) => request({ url: '/api/digital-resources/batch/tags', method: 'post', data })
export const batchDelete = (data) => request({ url: '/api/digital-resources/batch/delete', method: 'post', data })
