<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref } from 'vue'
import { onBeforeRouteLeave,useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { Picture,Refresh,Setting } from '@element-plus/icons-vue'
import RestorationSummaryBar from './components/restoration/RestorationSummaryBar.vue'
import RestorationResultList from './components/restoration/RestorationResultList.vue'
import RestorationWorkspace from './components/restoration/RestorationWorkspace.vue'
import RestorationAssistPanel from './components/restoration/RestorationAssistPanel.vue'
import { createEmptyRestoration,normalizeRestorations } from './restorationModel'
import {
    deleteRestorationMedia,deleteRestorationModel,deleteRestorationResult,
    getRestorationMediaContent,getRestorationWorkbench,saveRestorationWorkbench,
    uploadRestorationMedia,uploadRestorationModel,restoreRestorationVersion
} from '@/api/conservationRestoration'
import { getProcessMediaContent } from '@/api/conservationProcess'
import { getComparisonMediaContent } from '@/api/conservationComparison'
const route=useRoute(),router=useRouter(),projectId=computed(()=>Number(route.params.projectId)||null)
const loading=ref(true),saving=ref(false),error=ref(''),project=ref(null),context=ref(null),results=ref([]),activeId=ref(null),dirty=ref(false),listDrawer=ref(false),assistDrawer=ref(false),createDialog=ref(false),createStep=ref(0),workspace=ref(null)
const objectUrls=[]
const current=computed(()=>results.value.find(x=>x.id===activeId.value)||null)
const readOnly=computed(()=>false)
const form=reactive({mode:'manual',resultCode:'',resultName:'',restorationType:'digital_3d',restorationCategory:'structure',targetPart:'',restorationScope:'',restorationPurpose:'',principal:'',participantNames:'',stepIds:[],comparisonIds:[],diseaseIds:[],detectionIds:[],basisSummary:'',evidenceLevel:'B',confidenceLevel:'medium',uncertaintySummary:''})
const relevantSteps=computed(()=>context.value?.steps.filter(x=>x.generateRestorationResult||['filling','restoration','assembly','coloring','three_d_modeling','virtual_assembly','anchoring','evaluation'].includes(x.stepType))||[])
const availableComparisons=computed(()=>context.value?.comparisons.filter(x=>x.selectedForRestoration)||[])
const missing=computed(()=>{const r=current.value;if(!r)return[];const a=[],add=(key,label,tab,critical=true)=>a.push({key,label,tab,critical});if(!r.resultName)add('name','缺少成果名称','overview');if(!r.restorationType||!r.restorationCategory)add('type','缺少复原类型或类别','overview');if(!r.targetPart)add('part','缺少目标部位','overview');if(!r.restorationScope)add('scope','缺少复原范围','overview');if(!r.basisSummary)add('basis','缺少依据摘要','overview');if(!r.methodSummary)add('method','缺少方法摘要','resources');if(!r.resultSummary)add('result','缺少结果摘要','overview');if(!r.uncertaintySummary)add('uncertain','缺少不确定性说明','overview');if(!r.evidenceLevel||!r.confidenceLevel||r.confidenceLevel==='undetermined')add('grade','缺少证据等级或可信度','overview');if(!r.parts.length)add('parts','缺少组成部分','parts');r.parts.filter(x=>['evidence_based','inferred'].includes(x.partType)).forEach(x=>{if(!r.sources.some(s=>s.restorationPartId===x.id))add(`source-${x.id}`,`${x.partName}缺少依据`,'sources');if(x.partType==='inferred'&&!x.annotationText)add(`infer-${x.id}`,`${x.partName}未说明推测性质`,'parts')});r.parts.filter(x=>x.partType==='physical_completion').forEach(x=>{if(!x.materialName||!x.reversibleDescription||!x.distinguishable)add(`physical-${x.id}`,`${x.partName}材料、可逆性或可辨识性不完整`,'parts')});if(!r.media.some(x=>x.isPrimary)&&!r.models.some(x=>x.isPrimary))add('primary','缺少主成果图或主模型','resources');if(r.restorationType==='digital_3d'&&!r.models.some(x=>x.isPrimary&&x.scaleUnit))add('model','三维成果缺少主模型或比例单位','resources');if(!r.versions.some(x=>x.isCurrent))add('version','尚未设置当前版本','version');if(!r.evaluation.finalConclusion)add('evaluation','成果评价尚未填写','version',false);if(r.requiresMonitoring&&(!r.monitoring.partIds.length||!r.monitoring.indicators||!r.monitoring.cycle))add('monitoring','后续监测对象、指标或周期不完整','overview');return a})
const completeness=computed(()=>{const r=current.value;if(!r)return 0;let s=0;if(r.resultName&&r.targetPart&&r.restorationScope)s+=15;if(r.parts.length)s+=20;if(r.sources.length)s+=20;if(r.media.some(x=>x.isPrimary)||r.models.some(x=>x.isPrimary))s+=15;if(r.methodSummary&&r.methodParameters.length)s+=10;if(r.uncertaintySummary)s+=10;if(r.versions.some(x=>x.isCurrent)&&r.evaluation.finalConclusion)s+=10;return s})
const asObjectUrl=async(loader,id)=>{const response=await loader(id);const url=URL.createObjectURL(response.data);objectUrls.push(url);return url}
const hydrateMedia=async()=>{const jobs=[];context.value?.steps?.forEach(step=>step.media?.forEach(media=>jobs.push(asObjectUrl(getProcessMediaContent,media.id).then(url=>{media.fileUrl=media.thumbnailUrl=url}).catch(()=>{media.fileUrl=media.thumbnailUrl=''}))));context.value?.comparisons?.forEach(group=>group.images?.forEach(media=>jobs.push(asObjectUrl(getComparisonMediaContent,media.id).then(url=>{media.fileUrl=media.thumbnailUrl=url}).catch(()=>{media.fileUrl=media.thumbnailUrl=''}))));results.value.forEach(result=>result.media.forEach(media=>jobs.push(asObjectUrl(getRestorationMediaContent,media.id).then(url=>{media.fileUrl=media.thumbnailUrl=url}).catch(()=>{media.fileUrl=media.thumbnailUrl=''}))));await Promise.all(jobs)}
const load=async()=>{loading.value=true;error.value='';try{if(!projectId.value)throw Error('缺少保护修复项目ID');const response=await getRestorationWorkbench(projectId.value),data=response.data||{};project.value=data.project||null;context.value=data.context||null;results.value=normalizeRestorations(data.results||[]);await hydrateMedia();activeId.value=Number(route.query.resultId)||results.value[0]?.id;dirty.value=false}catch(e){error.value=e.message||'文物复原成果加载失败';ElMessage.error('数据加载失败，请稍后重试')}finally{loading.value=false}}
const applyResponse=async(data,id)=>{project.value=data.project||project.value;context.value=data.context||context.value;results.value=normalizeRestorations(data.results||[]);activeId.value=results.value.find(x=>x.id===id)?.id||results.value[0]?.id;await hydrateMedia()}
const save=async(show=true)=>{if(!current.value)return;saving.value=true;try{current.value.completionRate=completeness.value;current.value.recommendedResult=false;const id=activeId.value;const response=await saveRestorationWorkbench(projectId.value,results.value);await applyResponse(response.data||{},id);dirty.value=false;if(show)ElMessage.success('当前复原成果已保存到MySQL')}catch(e){ElMessage.error(e.message||'保存失败，请稍后重试')}finally{saving.value=false}}
const openCreate=mode=>{createStep.value=0;Object.assign(form,{mode,resultCode:`RR-${project.value.artifactCode.replace(/\W/g,'')}-${String(results.value.length+1).padStart(3,'0')}`,resultName:'',restorationType:'digital_3d',restorationCategory:'structure',targetPart:'',restorationScope:'',restorationPurpose:'',principal:project.value.principal,participantNames:'',stepIds:[],comparisonIds:[],diseaseIds:[],detectionIds:[],basisSummary:'',evidenceLevel:'B',confidenceLevel:'medium',uncertaintySummary:''});createDialog.value=true}
const create=()=>{const r=createEmptyRestoration(project.value,context.value?.process?.id);Object.assign(r,form);r.resultName=form.resultName?.trim()||`未命名复原成果草稿${results.value.length+1}`;const step=context.value?.steps?.find(x=>form.stepIds.includes(x.id)),cmp=context.value?.comparisons?.find(x=>form.comparisonIds.includes(x.id));if(step){r.targetPart||=step.targetPart;r.methodSummary=step.actualMethod||step.plannedMethod;r.diseaseIds=(step.relatedDiseases||[]).map(x=>x.diseaseRecordId);r.media=(step.media||[]).filter(x=>x.selectedForRestoration).map((x,i)=>({id:Date.now()+i,sourceMediaId:x.id,sourceBusinessType:'process_step',sourceBusinessId:step.id,mediaStage:x.mediaStage,mediaType:'image',fileName:x.fileName,fileUrl:x.fileUrl,thumbnailUrl:x.fileUrl,title:x.title,description:x.description,isPrimary:false,selectedForArchive:false,selectedAsMonitoringBaseline:false,sortOrder:i+1}))}if(cmp){r.targetPart||=cmp.targetPart;r.diseaseIds=(cmp.diseases||[]).map(x=>x.diseaseRecordId);r.media=(cmp.images||[]).map((x,i)=>({id:Date.now()+100+i,sourceMediaId:x.id,sourceBusinessType:'comparison',sourceBusinessId:cmp.id,mediaStage:x.imageStage==='after'?'final':x.imageStage,mediaType:'image',fileName:x.fileName,fileUrl:x.fileUrl,thumbnailUrl:x.thumbnailUrl,title:x.imageDescription,description:'引用前后对比影像',isPrimary:x.imageStage==='after',selectedForArchive:false,selectedAsMonitoringBaseline:false,sortOrder:i+1}))}r.versions=[{id:Date.now()+500,versionNo:'V1.0',versionName:'初始版本',versionType:'initial',changeDescription:'创建复原成果',evidenceLevel:r.evidenceLevel,confidenceLevel:r.confidenceLevel,isCurrent:true,isRecommended:false,creator:r.principal,createTime:new Date().toLocaleString('zh-CN',{hour12:false})}];results.value.unshift(r);activeId.value=r.id;createDialog.value=false;dirty.value=true}
const remove=async r=>{try{await ElMessageBox.confirm('仅删除该成果的数据展示记录，不删除修复过程和前后对比源数据。','删除成果',{type:'warning'});await deleteRestorationResult(r.id);results.value.splice(results.value.indexOf(r),1);activeId.value=results.value[0]?.id;dirty.value=false;ElMessage.success('复原成果已删除')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'删除失败')}}
const uploadMediaFile=async file=>{if(!current.value)return;try{if(dirty.value)await save(false);const data=new FormData();data.append('file',file);data.append('mediaStage','final');data.append('mediaType',file.type.startsWith('video/')?'video':'image');data.append('title',file.name);data.append('isPrimary',String(!current.value.media.length));const response=await uploadRestorationMedia(current.value.id,data),media=response.data;media.fileUrl=media.thumbnailUrl=await asObjectUrl(getRestorationMediaContent,media.id);current.value.media.push(media);ElMessage.success('成果媒体已写入MySQL')}catch(e){ElMessage.error(e.message||'媒体上传失败')}}
const uploadModelFile=async file=>{if(!current.value)return;try{if(dirty.value)await save(false);const data=new FormData();data.append('file',file);data.append('modelName',file.name);data.append('modelType','restored');data.append('scaleUnit','mm');data.append('coordinateSystem','项目局部坐标系');data.append('supportsLayer','true');data.append('supportsAnnotation','true');data.append('isPrimary',String(!current.value.models.length));const response=await uploadRestorationModel(current.value.id,data);current.value.models.push(response.data);ElMessage.success('三维模型已写入MySQL，可直接打开 WebGL 查看器')}catch(e){ElMessage.error(e.message||'模型上传失败')}}
const removeMedia=async media=>{try{await deleteRestorationMedia(media.id);current.value.media.splice(current.value.media.indexOf(media),1);ElMessage.success('成果媒体已删除')}catch(e){ElMessage.error(e.message||'删除失败')}}
const removeModel=async model=>{try{await deleteRestorationModel(model.id);current.value.models.splice(current.value.models.indexOf(model),1);ElMessage.success('三维模型已删除')}catch(e){ElMessage.error(e.message||'删除失败')}}
const restoreVersion=async versionId=>{if(!current.value)return;try{saving.value=true;const id=current.value.id;const response=await restoreRestorationVersion(id,versionId);await applyResponse(response.data||{},id);dirty.value=false;ElMessage.success('历史版本已恢复，模型和媒体文件保持不变')}catch(e){ElMessage.error(e.message||'历史版本恢复失败')}finally{saving.value=false}}
const nav=(target,id)=>{const map={disease:`/conservation/project/${projectId.value}/disease`,process:`/conservation/project/${projectId.value}/process?stepId=${id||current.value?.stepIds[0]||''}`,process_step:`/conservation/project/${projectId.value}/process?stepId=${id||''}`,comparison:`/conservation/project/${projectId.value}/comparison?comparisonId=${id||current.value?.comparisonIds[0]||''}`,archive:`/conservation/project/${projectId.value}/archive?section=restoration`,detection:'/detection/manage',experiment:'/detection/manage'};if(map[target])router.push(map[target])}
const confirmLeave=async()=>{if(!dirty.value)return true;try{await ElMessageBox.confirm('存在未保存修改，确认离开？','未保存提示',{type:'warning'});return true}catch{return false}}
onBeforeRouteLeave(async()=>{const ok=await confirmLeave();if(ok)dirty.value=false;return ok});const unload=e=>{if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(()=>{window.addEventListener('beforeunload',unload);load()});onBeforeUnmount(()=>{window.removeEventListener('beforeunload',unload);objectUrls.forEach(URL.revokeObjectURL)})
</script>
<template><div class="page"><el-skeleton v-if="loading" animated :rows="12" class="loading"/><el-result v-else-if="error" icon="error" title="文物复原成果加载失败" :sub-title="error"><template #extra><el-button type="primary" :icon="Refresh" @click="load">重新加载</el-button></template></el-result><el-result v-else-if="!project" icon="warning" title="未找到对应的保护修复项目"/><template v-else><RestorationSummaryBar :project="project" :results="results" :current="current" :saving="saving" :dirty="dirty" @create="openCreate('manual')" @from-steps="openCreate('step')" @from-comparisons="openCreate('comparison')" @save="save" @version="workspace?.newVersion(false)" @comparison="nav('comparison')" @archive="nav('archive')" @open-list="listDrawer=true"/><div v-if="current" class="body"><div class="left"><RestorationResultList :results="results" :active-id="activeId" @select="id=>{activeId=id;dirty=false}" @create="openCreate('manual')" @delete="remove"/></div><main><RestorationWorkspace ref="workspace" :result="current" :context="context" :read-only="readOnly" @dirty="dirty=true" @navigate="nav" @upload-media="uploadMediaFile" @upload-model="uploadModelFile" @delete-media="removeMedia" @delete-model="removeModel" @restore-version="restoreVersion"/></main><div class="right"><RestorationAssistPanel :result="current" :completeness="completeness" :missing-items="missing" :read-only="readOnly" @dirty="dirty=true" @locate="workspace?.switchTab($event)" /></div><el-button class="fab" circle type="primary" :icon="Setting" @click="assistDrawer=true"/></div><div v-else class="empty"><el-icon><Picture/></el-icon><h2>当前项目尚未建立文物复原成果</h2><p>可以从修复过程、修复前后对比或手工方式创建实体、二维或三维复原成果。</p><el-button type="primary" :disabled="!context?.process" @click="openCreate('step')">从修复步骤生成</el-button><el-button @click="openCreate('manual')">手工创建</el-button></div></template></div>
<el-drawer v-model="listDrawer" direction="ltr" size="315px" :with-header="false"><RestorationResultList :results="results" :active-id="activeId" @select="id=>{activeId=id;listDrawer=false}" @create="openCreate('manual')" @delete="remove"/></el-drawer><el-drawer v-model="assistDrawer" direction="rtl" size="300px"><RestorationAssistPanel v-if="current" :result="current" :completeness="completeness" :missing-items="missing" :read-only="readOnly" @dirty="dirty=true" @locate="workspace?.switchTab($event)"/></el-drawer>
<el-dialog v-model="createDialog" title="新建复原成果" width="min(850px,96vw)"><el-steps :active="createStep" finish-status="success"><el-step title="创建方式"/><el-step title="基本信息"/><el-step title="关联数据"/><el-step title="初始依据"/></el-steps><div class="create"><div v-if="createStep===0"><el-radio-group v-model="form.mode"><el-radio-button value="step">从修复步骤创建</el-radio-button><el-radio-button value="comparison">从前后对比创建</el-radio-button><el-radio-button value="manual">手工创建</el-radio-button></el-radio-group></div><el-form v-else label-position="top"><div class="form"><template v-if="createStep===1"><el-form-item label="成果编号"><el-input v-model="form.resultCode"/></el-form-item><el-form-item label="成果名称"><el-input v-model="form.resultName"/></el-form-item><el-form-item label="复原类型"><el-select v-model="form.restorationType"><el-option label="实体复原" value="physical"/><el-option label="二维数字" value="digital_2d"/><el-option label="三维数字" value="digital_3d"/><el-option label="实体与数字结合" value="hybrid"/><el-option label="学术推测" value="conceptual"/></el-select></el-form-item><el-form-item label="目标部位"><el-input v-model="form.targetPart"/></el-form-item><el-form-item class="wide" label="复原范围"><el-input v-model="form.restorationScope" type="textarea"/></el-form-item></template><template v-else-if="createStep===2"><el-form-item v-if="form.mode!=='comparison'" class="wide" label="修复步骤"><el-select v-model="form.stepIds" multiple><el-option v-for="x in relevantSteps" :key="x.id" :label="x.stepName" :value="x.id"/></el-select></el-form-item><el-form-item v-if="form.mode!=='step'" class="wide" label="前后对比"><el-select v-model="form.comparisonIds" multiple><el-option v-for="x in availableComparisons" :key="x.id" :label="x.comparisonTitle" :value="x.id"/></el-select></el-form-item></template><template v-else><el-form-item class="wide" label="依据摘要"><el-input v-model="form.basisSummary" type="textarea" :rows="3"/></el-form-item><el-form-item label="证据等级"><el-select v-model="form.evidenceLevel"><el-option v-for="x in ['A','B','C','D']" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="可信度"><el-select v-model="form.confidenceLevel"><el-option label="高" value="high"/><el-option label="中" value="medium"/><el-option label="低" value="low"/></el-select></el-form-item><el-form-item class="wide" label="不确定性说明"><el-input v-model="form.uncertaintySummary" type="textarea"/></el-form-item></template></div></el-form></div><template #footer><el-button v-if="createStep>0" @click="createStep--">上一步</el-button><el-button @click="createDialog=false">取消</el-button><el-button v-if="createStep<3" type="primary" @click="createStep++">下一步</el-button><el-button v-else type="primary" @click="create">创建成果</el-button></template></el-dialog>
</template>
<style scoped>.page{height:calc(100vh - 64px);display:flex;flex-direction:column;overflow:hidden;background:#eef1ef}.loading{margin:22px;padding:22px;background:#fff}.body{flex:1;min-height:0;display:grid;grid-template-columns:300px minmax(500px,1fr) 280px}.left,.right{min-width:0;overflow:hidden}.body>main{overflow:auto;min-width:0}.fab{display:none;position:fixed;right:22px;bottom:25px}.empty{flex:1;display:grid;place-content:center;justify-items:center;text-align:center}.empty>.el-icon{font-size:55px;color:#4d7869}.empty p{color:#84908c}.create{min-height:320px;padding:30px 5px}.form{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}.wide{grid-column:1/-1}.el-select{width:100%}@media(max-width:1280px){.body{grid-template-columns:290px minmax(480px,1fr)}.right{display:none}.fab{display:inline-flex}}@media(max-width:920px){.body{grid-template-columns:1fr}.left{display:none}.page{height:calc(100vh - 56px)}}@media(max-width:600px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
