<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref } from 'vue'
import { onBeforeRouteLeave,useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { Picture,Refresh,Setting } from '@element-plus/icons-vue'
import RestorationSummaryBar from './components/restoration/RestorationSummaryBar.vue'
import RestorationResultList from './components/restoration/RestorationResultList.vue'
import RestorationWorkspace from './components/restoration/RestorationWorkspace.vue'
import RestorationAssistPanel from './components/restoration/RestorationAssistPanel.vue'
import { mockProjects,createMockArchive,createMockArchiveWorkspace } from './archiveMock'
import { createEmptyRestoration,createMockRestorations,createRestorationContext } from './restorationMock'
import { USE_CONSERVATION_RESTORATION_MOCK } from '@/api/conservationRestoration'
const route=useRoute(),router=useRouter(),projectId=computed(()=>Number(route.params.projectId)||null)
const loading=ref(true),saving=ref(false),error=ref(''),project=ref(null),context=ref(null),results=ref([]),activeId=ref(null),dirty=ref(false),listDrawer=ref(false),assistDrawer=ref(false),createDialog=ref(false),createStep=ref(0),workspace=ref(null)
const storageKey=computed(()=>`conservation-restoration-workbench:${projectId.value}`)
const current=computed(()=>results.value.find(x=>x.id===activeId.value)||null)
const readOnly=computed(()=>['completed','reviewed','archived'].includes(current.value?.resultStatus))
const form=reactive({mode:'manual',resultCode:'',resultName:'',restorationType:'digital_3d',restorationCategory:'structure',targetPart:'',restorationScope:'',restorationPurpose:'',principal:'',participantNames:'',stepIds:[],comparisonIds:[],diseaseIds:[],detectionIds:[],basisSummary:'',evidenceLevel:'B',confidenceLevel:'medium',uncertaintySummary:''})
const relevantSteps=computed(()=>context.value?.steps.filter(x=>x.generateRestorationResult||['filling','restoration','assembly','coloring','three_d_modeling','virtual_assembly','anchoring','evaluation'].includes(x.stepType))||[])
const availableComparisons=computed(()=>context.value?.comparisons.filter(x=>x.selectedForRestoration)||[])
const missing=computed(()=>{const r=current.value;if(!r)return[];const a=[],add=(key,label,tab,critical=true)=>a.push({key,label,tab,critical});if(!r.resultName)add('name','缺少成果名称','overview');if(!r.targetPart)add('part','缺少目标部位','overview');if(!r.restorationScope)add('scope','缺少复原范围','overview');if(!r.basisSummary)add('basis','缺少依据摘要','overview');if(!r.methodSummary)add('method','缺少方法摘要','resources');if(!r.resultSummary)add('result','缺少结果摘要','overview');if(!r.uncertaintySummary)add('uncertain','缺少不确定性说明','overview');if(!r.parts.length)add('parts','缺少组成部分','parts');r.parts.filter(x=>['evidence_based','inferred'].includes(x.partType)).forEach(x=>{if(!r.sources.some(s=>s.restorationPartId===x.id))add(`source-${x.id}`,`${x.partName}缺少依据`,'sources');if(x.partType==='inferred'&&!x.annotationText)add(`infer-${x.id}`,`${x.partName}未说明推测性质`,'parts')});r.parts.filter(x=>x.partType==='physical_completion').forEach(x=>{if(!x.materialName||!x.reversibleDescription||!x.distinguishable)add(`physical-${x.id}`,`${x.partName}材料、可逆性或可辨识性不完整`,'parts')});if(!r.media.some(x=>x.isPrimary)&&!r.models.some(x=>x.isPrimary))add('primary','缺少主成果图或主模型','resources');if(r.restorationType==='digital_3d'&&!r.models.some(x=>x.isPrimary&&x.scaleUnit))add('model','三维成果缺少主模型或比例单位','resources');if(!r.versions.some(x=>x.isCurrent))add('version','尚未设置当前版本','version');if(!r.versions.some(x=>x.isRecommended))add('recommend','尚未设置推荐版本','version',false);if(!r.evaluation.finalConclusion)add('evaluation','成果评价尚未完成','version');return a})
const completeness=computed(()=>{const r=current.value;if(!r)return 0;let s=0;if(r.resultName&&r.targetPart&&r.restorationScope)s+=15;if(r.parts.length)s+=20;if(r.sources.length)s+=20;if(r.media.some(x=>x.isPrimary)||r.models.some(x=>x.isPrimary))s+=15;if(r.methodSummary&&r.methodParameters.length)s+=10;if(r.uncertaintySummary)s+=10;if(r.versions.some(x=>x.isCurrent)&&r.evaluation.finalConclusion)s+=10;return s})
const load=async()=>{loading.value=true;try{project.value=structuredClone(mockProjects[projectId.value]||null);if(!project.value)return;if(!USE_CONSERVATION_RESTORATION_MOCK)throw Error('真实接口未启用');if(projectId.value===5){context.value=null;results.value=[];return}context.value=createRestorationContext(project.value);const saved=JSON.parse(localStorage.getItem(storageKey.value)||'null');results.value=saved?.results||(projectId.value===1?createMockRestorations(project.value):[]);activeId.value=Number(route.query.resultId)||results.value[0]?.id;dirty.value=false}catch(e){error.value=e.message;ElMessage.error('数据加载失败，请稍后重试')}finally{loading.value=false}}
const sync=()=>{const summary={total:results.value.length,physical:results.value.filter(x=>x.restorationType==='physical').length,digital:results.value.filter(x=>x.restorationType.startsWith('digital')).length,completed:results.value.filter(x=>['completed','reviewed','archived'].includes(x.resultStatus)).length,processing:results.value.filter(x=>['draft','in_progress'].includes(x.resultStatus)).length,recommended:results.value.find(x=>x.recommendedResult)?.resultName||'',updateTime:new Date().toLocaleString('zh-CN',{hour12:false})};localStorage.setItem(`conservation-restoration-summary:${projectId.value}`,JSON.stringify(summary));localStorage.setItem(`conservation-restoration-monitoring:${projectId.value}`,JSON.stringify(results.value.filter(x=>x.requiresMonitoring)));const key=`conservation-archive-workbench:${projectId.value}`;const data=JSON.parse(localStorage.getItem(key)||'null')||{archive:createMockArchive(project.value),workspace:createMockArchiveWorkspace(project.value),revisions:[]};data.workspace.restorationResults=results.value.filter(x=>x.selectedForArchive).map(x=>({id:x.id,name:x.resultName,type:x.restorationType,status:x.resultStatus,confidence:x.confidenceLevel,image:x.media.find(m=>m.isPrimary)?.fileUrl,model:x.models.find(m=>m.isPrimary)?.fileName,version:x.currentVersion,description:x.evaluation.finalConclusion||x.resultSummary}));localStorage.setItem(key,JSON.stringify(data))}
const save=async(show=true)=>{if(!current.value)return;saving.value=true;await new Promise(r=>setTimeout(r,180));current.value.completionRate=completeness.value;current.value.updateTime=new Date().toLocaleString('zh-CN',{hour12:false});localStorage.setItem(storageKey.value,JSON.stringify({results:results.value}));sync();dirty.value=false;saving.value=false;if(show)ElMessage.success('当前复原成果已保存')}
const openCreate=mode=>{createStep.value=0;Object.assign(form,{mode,resultCode:`RR-${project.value.artifactCode.replace(/\W/g,'')}-${String(results.value.length+1).padStart(3,'0')}`,resultName:'',restorationType:'digital_3d',restorationCategory:'structure',targetPart:'',restorationScope:'',restorationPurpose:'',principal:project.value.principal,participantNames:'',stepIds:[],comparisonIds:[],diseaseIds:[],detectionIds:[],basisSummary:'',evidenceLevel:'B',confidenceLevel:'medium',uncertaintySummary:''});createDialog.value=true}
const create=()=>{if(!form.resultName)return ElMessage.warning('请填写成果名称');const r=createEmptyRestoration(project.value,context.value.process.id);Object.assign(r,form);const step=context.value.steps.find(x=>form.stepIds.includes(x.id)),cmp=context.value.comparisons.find(x=>form.comparisonIds.includes(x.id));if(step){r.targetPart||=step.targetPart;r.methodSummary=step.actualMethod||step.plannedMethod;r.diseaseIds=step.relatedDiseases.map(x=>x.diseaseRecordId);r.media=step.media.filter(x=>x.selectedForRestoration).map((x,i)=>({id:Date.now()+i,sourceMediaId:x.id,sourceBusinessType:'process_step',sourceBusinessId:step.id,mediaStage:x.mediaStage,mediaType:'image',fileName:x.fileName,fileUrl:x.fileUrl||'/mock/restoration-new/carriage.svg',thumbnailUrl:x.fileUrl||'/mock/restoration-new/carriage.svg',title:x.title,description:x.description,isPrimary:false}))}if(cmp){r.targetPart||=cmp.targetPart;r.diseaseIds=cmp.diseases.map(x=>x.diseaseRecordId);r.media=cmp.images.map((x,i)=>({id:Date.now()+i,sourceMediaId:x.sourceMediaId,sourceBusinessType:'comparison',sourceBusinessId:cmp.id,mediaStage:x.imageStage==='after'?'final':x.imageStage,mediaType:'image',fileName:x.fileName,fileUrl:x.fileUrl,thumbnailUrl:x.thumbnailUrl,title:x.imageDescription,description:'引用前后对比影像',isPrimary:x.imageStage==='after'}))}r.versions=[{id:Date.now(),versionNo:'V1.0',versionName:'初始版本',versionType:'initial',changeDescription:'创建复原成果',evidenceLevel:r.evidenceLevel,confidenceLevel:r.confidenceLevel,isCurrent:true,isRecommended:false,creator:r.principal,createTime:new Date().toLocaleString('zh-CN',{hour12:false})}];results.value.unshift(r);activeId.value=r.id;createDialog.value=false;dirty.value=true}
const complete=async()=>{const critical=missing.value.filter(x=>x.critical);if(critical.length)return ElMessageBox.alert(critical.map(x=>x.label).join('\n'),'暂不能完成',{type:'warning'});current.value.resultStatus='completed';current.value.completionDate=new Date().toISOString().slice(0,10);current.value.completionRate=100;await save(false);ElMessage.success('成果已完成并同步总览、档案和监测摘要')}
const remove=async r=>{if(r.selectedForArchive||r.recommendedResult||r.resultStatus==='archived')return ElMessage.warning('请先解除档案、推荐或归档状态');try{await ElMessageBox.confirm('仅删除成果关联，不删除任何源数据。','删除成果',{type:'warning'});results.value.splice(results.value.indexOf(r),1);activeId.value=results.value[0]?.id;localStorage.setItem(storageKey.value,JSON.stringify({results:results.value}));sync()}catch{}}
const nav=(target,id)=>{const map={disease:`/conservation/project/${projectId.value}/disease`,process:`/conservation/project/${projectId.value}/process?stepId=${id||current.value?.stepIds[0]||''}`,process_step:`/conservation/project/${projectId.value}/process?stepId=${id||''}`,comparison:`/conservation/project/${projectId.value}/comparison?comparisonId=${id||current.value?.comparisonIds[0]||''}`,archive:`/conservation/project/${projectId.value}/archive?section=restoration`,detection:'/detection/manage',experiment:'/detection/manage'};if(map[target])router.push(map[target])}
const confirmLeave=async()=>{if(!dirty.value)return true;try{await ElMessageBox.confirm('存在未保存修改，确认离开？','未保存提示',{type:'warning'});return true}catch{return false}}
onBeforeRouteLeave(async()=>{const ok=await confirmLeave();if(ok)dirty.value=false;return ok});const unload=e=>{if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(()=>{window.addEventListener('beforeunload',unload);load()});onBeforeUnmount(()=>window.removeEventListener('beforeunload',unload))
</script>
<template><div class="page"><el-skeleton v-if="loading" animated :rows="12" class="loading"/><el-result v-else-if="error" icon="error" title="文物复原成果加载失败" :sub-title="error"><template #extra><el-button type="primary" :icon="Refresh" @click="load">重新加载</el-button></template></el-result><el-result v-else-if="!project" icon="warning" title="未找到对应的保护修复项目"/><el-result v-else-if="!context" icon="warning" title="当前项目尚未建立修复过程"><template #extra><el-button type="primary" @click="nav('process')">前往修复过程记录</el-button></template></el-result><template v-else><RestorationSummaryBar :project="project" :results="results" :current="current" :saving="saving" :dirty="dirty" @create="openCreate('manual')" @from-steps="openCreate('step')" @from-comparisons="openCreate('comparison')" @save="save" @complete="complete" @version="workspace?.newVersion(false)" @comparison="nav('comparison')" @archive="nav('archive')" @open-list="listDrawer=true"/><div v-if="current" class="body"><div class="left"><RestorationResultList :results="results" :active-id="activeId" @select="id=>{activeId=id;dirty=false}" @create="openCreate('manual')" @delete="remove"/></div><main><RestorationWorkspace ref="workspace" :result="current" :context="context" :read-only="readOnly" @dirty="dirty=true" @navigate="nav"/></main><div class="right"><RestorationAssistPanel :result="current" :completeness="completeness" :missing-items="missing" :read-only="readOnly" @dirty="dirty=true" @locate="workspace?.switchTab($event)" /></div><el-button class="fab" circle type="primary" :icon="Setting" @click="assistDrawer=true"/></div><div v-else class="empty"><el-icon><Picture/></el-icon><h2>当前项目尚未建立文物复原成果</h2><p>可以从修复过程、修复前后对比或手工方式创建实体、二维或三维复原成果。</p><el-button type="primary" @click="openCreate('step')">从修复步骤生成</el-button><el-button @click="openCreate('manual')">手工创建</el-button></div></template></div>
<el-drawer v-model="listDrawer" direction="ltr" size="315px" :with-header="false"><RestorationResultList :results="results" :active-id="activeId" @select="id=>{activeId=id;listDrawer=false}" @create="openCreate('manual')" @delete="remove"/></el-drawer><el-drawer v-model="assistDrawer" direction="rtl" size="300px"><RestorationAssistPanel v-if="current" :result="current" :completeness="completeness" :missing-items="missing" :read-only="readOnly" @dirty="dirty=true" @locate="workspace?.switchTab($event)"/></el-drawer>
<el-dialog v-model="createDialog" title="新建复原成果" width="min(850px,96vw)"><el-steps :active="createStep" finish-status="success"><el-step title="创建方式"/><el-step title="基本信息"/><el-step title="关联数据"/><el-step title="初始依据"/></el-steps><div class="create"><div v-if="createStep===0"><el-radio-group v-model="form.mode"><el-radio-button value="step">从修复步骤创建</el-radio-button><el-radio-button value="comparison">从前后对比创建</el-radio-button><el-radio-button value="manual">手工创建</el-radio-button></el-radio-group></div><el-form v-else label-position="top"><div class="form"><template v-if="createStep===1"><el-form-item label="成果编号"><el-input v-model="form.resultCode"/></el-form-item><el-form-item label="成果名称"><el-input v-model="form.resultName"/></el-form-item><el-form-item label="复原类型"><el-select v-model="form.restorationType"><el-option label="实体复原" value="physical"/><el-option label="二维数字" value="digital_2d"/><el-option label="三维数字" value="digital_3d"/><el-option label="实体与数字结合" value="hybrid"/><el-option label="学术推测" value="conceptual"/></el-select></el-form-item><el-form-item label="目标部位"><el-input v-model="form.targetPart"/></el-form-item><el-form-item class="wide" label="复原范围"><el-input v-model="form.restorationScope" type="textarea"/></el-form-item></template><template v-else-if="createStep===2"><el-form-item v-if="form.mode!=='comparison'" class="wide" label="修复步骤"><el-select v-model="form.stepIds" multiple><el-option v-for="x in relevantSteps" :key="x.id" :label="x.stepName" :value="x.id"/></el-select></el-form-item><el-form-item v-if="form.mode!=='step'" class="wide" label="前后对比"><el-select v-model="form.comparisonIds" multiple><el-option v-for="x in availableComparisons" :key="x.id" :label="x.comparisonTitle" :value="x.id"/></el-select></el-form-item></template><template v-else><el-form-item class="wide" label="依据摘要"><el-input v-model="form.basisSummary" type="textarea" :rows="3"/></el-form-item><el-form-item label="证据等级"><el-select v-model="form.evidenceLevel"><el-option v-for="x in ['A','B','C','D']" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="可信度"><el-select v-model="form.confidenceLevel"><el-option label="高" value="high"/><el-option label="中" value="medium"/><el-option label="低" value="low"/></el-select></el-form-item><el-form-item class="wide" label="不确定性说明"><el-input v-model="form.uncertaintySummary" type="textarea"/></el-form-item></template></div></el-form></div><template #footer><el-button v-if="createStep>0" @click="createStep--">上一步</el-button><el-button @click="createDialog=false">取消</el-button><el-button v-if="createStep<3" type="primary" @click="createStep++">下一步</el-button><el-button v-else type="primary" @click="create">创建成果</el-button></template></el-dialog>
</template>
<style scoped>.page{height:calc(100vh - 64px);display:flex;flex-direction:column;overflow:hidden;background:#eef1ef}.loading{margin:22px;padding:22px;background:#fff}.body{flex:1;min-height:0;display:grid;grid-template-columns:300px minmax(500px,1fr) 280px}.left,.right{min-width:0;overflow:hidden}.body>main{overflow:auto;min-width:0}.fab{display:none;position:fixed;right:22px;bottom:25px}.empty{flex:1;display:grid;place-content:center;justify-items:center;text-align:center}.empty>.el-icon{font-size:55px;color:#4d7869}.empty p{color:#84908c}.create{min-height:320px;padding:30px 5px}.form{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}.wide{grid-column:1/-1}.el-select{width:100%}@media(max-width:1280px){.body{grid-template-columns:290px minmax(480px,1fr)}.right{display:none}.fab{display:inline-flex}}@media(max-width:920px){.body{grid-template-columns:1fr}.left{display:none}.page{height:calc(100vh - 56px)}}@media(max-width:600px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
