<script setup>
import { computed, ref } from 'vue'
import { Bell, CircleCheck, Clock, Collection, Search } from '@element-plus/icons-vue'
const props = defineProps({ plans: { type: Array, default: () => [] }, activePlanId: Number, activeTargetId: Number })
defineEmits(['select-plan', 'select-target', 'add-target'])
const keyword = ref(''), status = ref(''), risk = ref('')
const typeMap = { disease: '病害', repair_part: '修复部位', restoration_part: '复原补配', environment: '环境', artifact: '文物整体' }
const filtered = computed(() => props.plans.map(plan => ({ ...plan, filteredTargets: plan.targets.filter(x => (!keyword.value || `${x.targetName}${x.targetPart}${x.targetLocation}`.includes(keyword.value)) && (!risk.value || x.riskLevel === risk.value)) })).filter(plan => !status.value || plan.planStatus === status.value))
const statusMap = { draft: ['草稿', 'info'], active: ['执行中', 'success'], paused: ['已暂停', 'warning'], terminated: ['已终止', 'danger'], archived: ['已归档', 'info'] }
const riskText = { high: '高', medium: '中', low: '低' }
</script>
<template>
<aside class="panel"><header><div><small>PLAN & TARGET</small><h3>计划与监测对象</h3></div><el-button link type="primary" @click="$emit('add-target')">+ 对象</el-button></header>
<el-input v-model="keyword" :prefix-icon="Search" clearable placeholder="搜索计划、部位或对象"/><div class="filters"><el-select v-model="status" clearable placeholder="计划状态"><el-option v-for="(x,k) in statusMap" :key="k" :label="x[0]" :value="k"/></el-select><el-select v-model="risk" clearable placeholder="风险"><el-option label="高风险" value="high"/><el-option label="中风险" value="medium"/><el-option label="低风险" value="low"/></el-select></div>
<div class="list"><article v-for="plan in filtered" :key="plan.id" class="plan" :class="{active:plan.id===activePlanId}" @click="$emit('select-plan',plan.id)"><div class="plan-title"><Collection/><div><b>{{ plan.planName }}</b><small>{{ plan.planCode }}</small></div><el-tag size="small" :type="statusMap[plan.planStatus]?.[1]">{{ statusMap[plan.planStatus]?.[0] }}</el-tag></div><div class="meta"><span><Clock/> {{ plan.defaultFrequencyValue }}{{ plan.defaultFrequencyUnit==='month'?'个月':'天' }}</span><span><Bell/> {{ plan.openAlertCount || 0 }}</span><span><CircleCheck/> {{ plan.completionRate }}%</span></div><div v-if="plan.id===activePlanId" class="targets" @click.stop><button v-for="x in plan.filteredTargets" :key="x.id" :class="{selected:x.id===activeTargetId}" @click="$emit('select-target',x.id)"><i :class="x.riskLevel">{{ riskText[x.riskLevel] }}</i><span><b>{{ x.targetName }}</b><small>{{ typeMap[x.targetType] }} · {{ x.currentStatus }}</small></span><em>{{ x.indicators.length }}</em></button><el-empty v-if="!plan.filteredTargets.length" description="无匹配对象" :image-size="42"/></div></article></div></aside>
</template>
<style scoped>
.panel{height:100%;min-height:0;background:#fff;border:1px solid #dde5e2;display:flex;flex-direction:column}.panel>header{display:flex;justify-content:space-between;align-items:center;padding:16px;border-bottom:1px solid #e8edeb}.panel header h3{margin:2px 0;font-size:15px;color:#29453e}.panel header small{font-size:9px;color:#8aa098;letter-spacing:.12em}.panel>:deep(.el-input){margin:12px;width:auto}.filters{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:0 12px 12px}.list{min-height:0;overflow:auto;padding:0 8px 12px}.plan{margin-bottom:8px;border:1px solid #e5e9e8;border-radius:5px;cursor:pointer}.plan.active{border-color:#6e9b8e;box-shadow:0 0 0 1px #6e9b8e inset}.plan-title{display:flex;align-items:flex-start;gap:8px;padding:12px}.plan-title>svg{width:16px;color:#658c80}.plan-title>div{min-width:0;flex:1}.plan-title b,.plan-title small{display:block}.plan-title b{font-size:12px;color:#344640;line-height:1.45}.plan-title small{margin-top:3px;font-size:9px;color:#9aa7a3}.meta{display:flex;gap:10px;padding:0 12px 10px;font-size:9px;color:#71827c}.meta span{display:flex;align-items:center;gap:3px}.meta svg{width:11px}.targets{border-top:1px solid #edf0ef;padding:6px;background:#f8faf9}.targets button{width:100%;border:0;border-bottom:1px solid #e9edeb;background:transparent;padding:9px 7px;display:flex;align-items:center;gap:8px;text-align:left;cursor:pointer}.targets button:last-child{border:0}.targets button.selected{background:#e8f1ee}.targets i{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;font-style:normal;font-size:9px;color:white}.targets i.high{background:#ba594e}.targets i.medium{background:#c98e42}.targets i.low{background:#5f9480}.targets span{min-width:0;flex:1}.targets b,.targets small{display:block}.targets b{font-size:11px;color:#3a4944}.targets small{margin-top:3px;font-size:9px;color:#87938f}.targets em{font-style:normal;font-size:9px;color:#6b8179;background:white;border:1px solid #dce4e1;padding:1px 5px;border-radius:8px}
</style>
