server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/nwsite?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:disease-media-schema.sql
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB




mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和驼峰命名的转换
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.itheima.bigevent.pojo
