<script setup>
import { computed } from 'vue'
import { Warning } from '@element-plus/icons-vue'
const props=defineProps({result:{type:Object,required:true},completeness:{type:Number,default:0},missingItems:{type:Array,default:()=>[]},readOnly:Boolean})
defineEmits(['dirty','locate','navigate'])
const confidenceMap={high:'高',medium:'中',low:'低',undetermined:'未确定'}
const typeDefs=[['original','原始保存','#315f51'],['repaired','原件修复','#547b70'],['physical_completion','实体补配','#aa7944'],['evidence_based','证据复原','#658ba1'],['inferred','推测复原','#8b6685'],['uncertain','无法确定','#8b908e']]
const ratios=computed(()=>typeDefs.map(([key,label,color])=>({key,label,color,value:props.result.parts.filter(x=>x.partType===key).reduce((s,x)=>s+(Number(x.percentageValue)||0),0)})))
</script>
<template><aside class="assist">
    <section class="grade"><div><span>证据等级</span><b>{{ result.evidenceLevel||'-' }}</b></div><div><span>可信度</span><b>{{ confidenceMap[result.confidenceLevel] }}</b></div><p>{{ result.basisSummary||'尚未填写复原依据摘要' }}</p></section>
    <section><h3>组成比例</h3><div v-for="item in ratios" :key="item.key" class="ratio"><div><i :style="{background:item.color}"></i><span>{{ item.label }}</span><b>{{ item.value }}%</b></div><el-progress :percentage="Math.min(100,item.value)" :show-text="false" :stroke-width="5" :color="item.color" /></div><small>比例仅用于成果表达与管理参考，不一定等同于精确体积比例。</small></section>
    <section><h3>关联数据</h3><div class="counts"><span>病害<b>{{ result.diseaseIds.length }}</b></span><span>修复步骤<b>{{ result.stepIds.length }}</b></span><span>前后对比<b>{{ result.comparisonIds.length }}</b></span><span>依据<b>{{ result.sources.length }}</b></span><span>组成部分<b>{{ result.parts.length }}</b></span><span>影像<b>{{ result.media.length }}</b></span><span>模型<b>{{ result.models.length }}</b></span><span>版本<b>{{ result.versions.length }}</b></span></div></section>
    <section><div class="section-title"><h3>完整度</h3><b>{{ completeness }}%</b></div><el-progress :percentage="completeness" :stroke-width="8" :color="completeness>=85?'#4a7b69':'#b08049'" /><small>依据成果类型动态计算，不能手工填写。</small></section>
    <section><div class="section-title"><h3>缺失项</h3><el-tag :type="missingItems.length?'warning':'success'" size="small">{{ missingItems.length }}项</el-tag></div><button v-for="item in missingItems" :key="item.key" class="missing" @click="$emit('locate',item.tab)"><el-icon><Warning/></el-icon><span>{{ item.label }}</span><i>{{ item.critical?'关键':'提示' }}</i></button><div v-if="!missingItems.length" class="complete">当前可视化资料的关键数据已齐全。</div></section>
    <section><h3>数据使用状态</h3><label><span>收入保护修复档案</span><el-switch v-model="result.selectedForArchive" :disabled="readOnly" @change="$emit('dirty')" /></label><label><span>需要后续监测</span><el-switch v-model="result.requiresMonitoring" :disabled="readOnly" @change="$emit('dirty')" /></label><div v-if="result.requiresMonitoring" class="monitoring-form"><span>监测组成部分</span><el-select v-model="result.monitoring.partIds" multiple :disabled="readOnly" @change="$emit('dirty')"><el-option v-for="part in result.parts" :key="part.id" :label="part.partName" :value="part.id"/></el-select><span>监测指标</span><el-input v-model="result.monitoring.indicators" type="textarea" :disabled="readOnly" @input="$emit('dirty')"/><span>建议周期</span><el-input v-model="result.monitoring.cycle" :disabled="readOnly" @input="$emit('dirty')"/><span>基准图片</span><el-select v-model="result.monitoring.baselineMediaId" clearable :disabled="readOnly" @change="$emit('dirty')"><el-option v-for="media in result.media" :key="media.id" :label="media.title||media.fileName" :value="media.id"/></el-select><span>预警条件</span><el-input v-model="result.monitoring.warningConditions" type="textarea" :disabled="readOnly" @input="$emit('dirty')"/><span>监测说明</span><el-input v-model="result.monitoring.note" type="textarea" :disabled="readOnly" @input="$emit('dirty')"/></div></section>
</aside></template>
<style scoped>
.monitoring-form{display:grid;gap:5px;margin-top:10px;padding-top:10px;border-top:1px dashed #d9e0dc}.monitoring-form>span{margin-top:4px;color:#75817c;font-size:9px}.monitoring-form :deep(.el-select){width:100%}
.assist{height:100%;overflow-y:auto;padding:0 15px 30px;background:#fafbfa;border-left:1px solid #dfe4e1}section{padding:17px 0;border-bottom:1px solid #e2e7e4}h3{margin:0 0 10px;color:#35473f;font-size:12px}.grade{display:grid;grid-template-columns:1fr 1fr;gap:8px}.grade>div{padding:12px;text-align:center;background:#eff5f2}.grade span,.grade b{display:block}.grade span{color:#84908b;font-size:9px}.grade b{margin-top:4px;color:#356856;font-size:23px}.grade p{grid-column:1/-1;margin:3px 0;color:#717d78;font-size:9px;line-height:1.6}.ratio{margin:7px 0}.ratio>div{display:grid;grid-template-columns:8px 1fr auto;gap:6px;align-items:center;margin-bottom:3px;color:#69746f;font-size:9px}.ratio i{width:8px;height:8px;border-radius:2px}.ratio b{color:#485750}small{display:block;margin-top:8px;color:#9aa29f;font-size:9px;line-height:1.5}.counts{display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px}.counts span{padding:7px;background:#f1f4f2;color:#8a9490;font-size:8px}.counts b{display:block;margin-top:2px;color:#40574e;font-size:14px}.section-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}.section-title h3{margin:0}.section-title>b{color:#3e725f;font-size:18px}.missing{width:100%;display:grid;grid-template-columns:15px 1fr auto;gap:6px;align-items:center;margin:5px 0;padding:8px;border:0;text-align:left;color:#795f42;background:#fff8ed;cursor:pointer}.missing span{font-size:9px}.missing i{color:#ad7c46;font-size:8px;font-style:normal}.complete{padding:9px;color:#42705e;background:#edf7f2;font-size:9px}section>label{display:flex;justify-content:space-between;align-items:center;padding:6px 0;color:#65716c;font-size:9px}
</style>
